-- apply_trims.lua — PLAN 1b.3 (2026-09-19): the ABSOLUTE trims onto the rack.
-- GENERATED by tools/gen_apply_trims.js from bank/trims.json — do not edit the table by hand.
-- Idempotent, self-reporting, and it NEVER saves: his CTRL+S.
--
-- The target (RUNNING_LOG §83): a 9-voice tutti at -20 LUFS-S, so each voice at
-- -29.54 LUFS = -31.84 dB on the instrument card's scale. Every instrument in this table
-- comes DOWN: the rack was 7–21 dB hot because 0d balanced it relatively, through a REC bus trimmed
-- 12 dB down, with nothing saying how loud the ensemble should BE (§76).
--
-- Each row: the Reaper FADER carries up to +12 dB (its ceiling); any remainder goes into a stock
-- "JS: Volume Adjustment" (utility/volume) FX on the track — Reaper-side, no MIDI binding, so no CC7 can
-- ever overwrite it (ARO's own gain is bound to CC7 and tops out at unity — §58; #5's SI2 parts had the same
-- trap). A track with no remainder gets no FX; an existing one is set to 0 rather than removed.
-- The SI2 `b` instances carry their instrument's trim too — the same instrument, its curve copies — and so
-- do **Horn SI2 high** and **Horn SI2 b high**, the ReaPitch path of 1a.1, which 0d's hand-typed table
-- predated and which have therefore never been trimmed at all.
--   node tools/reaper_job.js run reaper/bridge/jobs/apply_trims.lua
local JS_NAME = 'utility/volume'
local TRIMS = {
  { name = "English Horn XS", faderDb = -13.98, extraDb = 0.00 },   -- English Horn: was 0.00, -13.98
  { name = "Bassoon SI2", faderDb = -18.81, extraDb = 0.00 },   -- Bassoon: was -7.79, -11.02
  { name = "Bassoon SI2 b", faderDb = -18.81, extraDb = 0.00 },   -- Bassoon: was -7.79, -11.02
  { name = "Horn SI2", faderDb = -12.21, extraDb = 0.00 },   -- Horn: was -0.01, -12.20
  { name = "Horn SI2 b", faderDb = -12.21, extraDb = 0.00 },   -- Horn: was -0.01, -12.20
  { name = "Horn SI2 high", faderDb = -12.21, extraDb = 0.00 },   -- Horn: was -0.01, -12.20
  { name = "Horn SI2 b high", faderDb = -12.21, extraDb = 0.00 },   -- Horn: was -0.01, -12.20
  { name = "Trumpet SI2", faderDb = -9.53, extraDb = 0.00 },   -- Trumpet: was -0.17, -9.36
  { name = "Trumpet SI2 b", faderDb = -9.53, extraDb = 0.00 },   -- Trumpet: was -0.17, -9.36
  { name = "Cello XS", faderDb = -3.87, extraDb = 0.00 },   -- Cello: was 10.29, -14.16
  { name = "Bass XS", faderDb = -2.97, extraDb = 0.00 },   -- D. Bass: was 5.25, -8.22
  { name = "Finger Cymbals ARO", faderDb = 5.90, extraDb = 0.00 },   -- Finger Cymbals: was 15.29, -9.39
  { name = "Bell Tree ARO", faderDb = 8.71, extraDb = 0.00 },   -- Bell Tree: was 21.26, -12.55
  { name = "Sleigh Bells ARO", faderDb = -3.51, extraDb = 0.00 },   -- Sleigh Bells: was 17.81, -21.32
  { name = "Triangles ARO", faderDb = 11.62, extraDb = 0.00 },   -- Triangles: was 22.23, -10.61
  { name = "Tambourines ARO", faderDb = 6.66, extraDb = 0.00 },   -- Tambourines: was 15.76, -9.10
  { name = "Castanets ARO", faderDb = 12.00, extraDb = 12.33 },   -- Castanets: was 32.02, -7.69
  { name = "Claves ARO", faderDb = 12.00, extraDb = 4.06 },   -- Claves: was 25.64, -9.58
  { name = "Shakers ARO", faderDb = 12.00, extraDb = 11.22 },   -- Shakers: was 29.82, -6.60
  { name = "Brake Drums ARO", faderDb = 3.81, extraDb = 0.00 },   -- Brake Drums: was 13.03, -9.22
  { name = "Crashers and Stack ARO", faderDb = 6.83, extraDb = 0.00 },   -- Crashers and Stack: was 16.12, -9.29
  { name = "Wood Blocks ARO", faderDb = 7.05, extraDb = 0.00 },   -- Wood Blocks: was 15.43, -8.38
  { name = "Bass Drum Alt ARO", faderDb = -4.29, extraDb = 0.00 },   -- Bass Drum Alt: was 5.60, -9.89
  { name = "Temple Bowls ARO", faderDb = 11.53, extraDb = 0.00 },   -- Temple Bowls: was 21.38, -9.85
  { name = "Tam Tams ARO", faderDb = -0.79, extraDb = 0.00 },   -- Tam Tams: was 11.32, -12.11
  { name = "Vibraphone XS", faderDb = 2.81, extraDb = 0.00 },   -- Vibraphone: was -6.62, +9.43
}
local function findTrack(name)
  for i = 0, reaper.CountTracks(0) - 1 do
    local tr = reaper.GetTrack(0, i); local _, n = reaper.GetTrackName(tr)
    if n == name then return tr end
  end
end
local function findFx(tr)
  for i = 0, reaper.TrackFX_GetCount(tr) - 1 do
    local _, nm = reaper.TrackFX_GetFXName(tr, i, '')
    if nm:lower():find('volume adjustment', 1, true) or nm:lower():find('utility/volume', 1, true) then return i end
  end
end
local done, missing = {}, {}
for _, r in ipairs(TRIMS) do
  local tr = findTrack(r.name)
  if not tr then missing[#missing + 1] = r.name
  else
    reaper.SetMediaTrackInfo_Value(tr, 'D_VOL', 10 ^ (r.faderDb / 20))
    local fx = findFx(tr)
    local fxDb, fxParam = nil, nil
    if r.extraDb ~= 0 or fx then
      if not fx then fx = reaper.TrackFX_AddByName(tr, JS_NAME, false, -1) end
      if fx and fx >= 0 then
        reaper.TrackFX_SetEnabled(tr, fx, true)
        reaper.TrackFX_SetParam(tr, fx, 0, r.extraDb)
        local _, pn = reaper.TrackFX_GetParamName(tr, fx, 0, '')
        fxDb, fxParam = reaper.TrackFX_GetParam(tr, fx, 0), pn
      else fx = nil end
    end
    local volDb = 20 * math.log(reaper.GetMediaTrackInfo_Value(tr, 'D_VOL'), 10)
    done[#done + 1] = { name = r.name, faderAsked = r.faderDb, faderDb = math.floor(volDb * 100 + 0.5) / 100,
                        extraAsked = r.extraDb, fxIndex = fx, fxDb = fxDb and math.floor(fxDb * 100 + 0.5) / 100 or nil, fxParam = fxParam,
                        ok = math.abs(volDb - r.faderDb) < 0.05 and (r.extraDb == 0 or (fxDb ~= nil and math.abs(fxDb - r.extraDb) < 0.05)) }
  end
end
local allOk = #missing == 0
for _, d in ipairs(done) do if not d.ok then allOk = false end end
return { ok = allOk, applied = #done, missingTracks = missing, tracks = done, note = 'not saved — his CTRL+S' }
