#!/usr/bin/env node
// apply_ranges.js — PLAN 0d (2026-09-06): the measured ranges (bank/technique_ranges.json, from `balance_schedule.js --ranges` +
// `analyze_balance.py --ranges`) written into sandbox/instruments.js as a generated block, MEASURED_RANGES, applied to the
// techniques at load by applyMeasuredRanges(). The recipe's own rangeLow / rangeHigh stay as the keyboard zone; a measured
// technique's range REPLACES them wherever it sounds narrower — never wider than the zone. Re-run after every ranges probe.
//
//   node tools/apply_ranges.js [--in bank/technique_ranges.json] [--dry]
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
const opt = (k, d) => { const i = args.indexOf('--' + k); return i >= 0 && args[i + 1] != null ? args[i + 1] : d; };
const IN = path.resolve(ROOT, opt('in', 'bank/technique_ranges.json')), RECIPE = path.join(ROOT, 'sandbox', 'instruments.js');
const R = JSON.parse(fs.readFileSync(IN, 'utf8'));
const BEGIN = '// ---- MEASURED RANGES (generated by tools/apply_ranges.js — do not edit by hand) ----', END = '// ---- end of the measured ranges ----';

const lines = ['const MEASURED_RANGES = {   // measured ' + (R.measuredAt || '').slice(0, 16) + ' (' + R.wav + '): per technique [lo, hi] of the keys that sounded; silent keys inside the span listed'];
let count = 0;
for (const [inst, techs] of Object.entries(R.instruments || {})) {
    const items = [];
    for (const [key, d] of Object.entries(techs)) {
        if (d.lo == null || d.hi == null) { items.push('    ' + JSON.stringify(key) + ': null,   // NOTHING sounded — check the routing or the preset'); continue; }
        const gaps = (d.gapsInside || []).length ? ', gaps: ' + JSON.stringify(d.gapsInside) : '';
        items.push('    ' + JSON.stringify(key) + ': { lo: ' + d.lo + ', hi: ' + d.hi + gaps + ' },' + (d.silent && d.silent.length ? '   // silent: ' + d.silent.join(' ') : ''));
        count++;
    }
    lines.push('  ' + inst + ': {'); lines.push(...items); lines.push('  },');
}
lines.push('};');
lines.push('function applyMeasuredRanges(all, measured) {   // the measured span replaces the keyboard zone where it is narrower');
lines.push('  for (const [inst, techs] of Object.entries(measured || {})) {');
lines.push('    const I = all[inst]; if (!I || !I.techniques) continue;');
lines.push('    for (const q of I.techniques) {');
lines.push('      const m = techs[q.key]; if (!m) continue;');
lines.push('      const lo = q.rangeLow != null ? q.rangeLow : I.rangeLow, hi = q.rangeHigh != null ? q.rangeHigh : I.rangeHigh;');
lines.push('      q.zoneLow = lo; q.zoneHigh = hi; q.measured = true;');
lines.push('      q.rangeLow = Math.max(lo, m.lo); q.rangeHigh = Math.min(hi, m.hi);');
lines.push('      if (m.gaps && m.gaps.length) q.silentKeys = m.gaps.slice();');
lines.push('    }');
lines.push('  }');
lines.push('}');
lines.push('applyMeasuredRanges(INSTRUMENTS, MEASURED_RANGES);');
const block = BEGIN + '\n' + lines.join('\n') + '\n' + END + '\n';

let src = fs.readFileSync(RECIPE, 'utf8');
const i = src.indexOf(BEGIN), j = src.indexOf(END);
let out;
if (i >= 0 && j > i) out = src.slice(0, i) + block + src.slice(j + END.length + 1);
else {
    // first time: after the INSTRUMENTS table and its helpers, before the hardware-capture lines at the file's end
    const anchor = '// Hardware capture input.';
    const k = src.indexOf(anchor);
    if (k < 0) throw new Error('anchor for the block not found in the recipe');
    out = src.slice(0, k) + block + '\n' + src.slice(k);
}
if (args.includes('--dry')) { console.log(block); console.log(count + ' measured techniques (dry run, nothing written)'); process.exit(0); }
fs.writeFileSync(RECIPE, out);
// prove the recipe still evaluates and the ranges took
const vm = require('vm');
const I = vm.runInNewContext(out + '\n;INSTRUMENTS;', {});
const applied = [];
for (const [inst, techs] of Object.entries(R.instruments || {})) for (const key of Object.keys(techs)) { const q = (I[inst].techniques || []).find(x => x.key === key); if (q && q.measured) applied.push(inst + ':' + key + ' ' + q.rangeLow + '-' + q.rangeHigh + (q.silentKeys ? ' (gaps ' + q.silentKeys.join(' ') + ')' : '')); }
console.log(count + ' measured techniques written into sandbox/instruments.js; applied at load:');
applied.forEach(a => console.log('  ' + a));
