#!/usr/bin/env node
// apply_perc.js — PLAN 0c (2026-09-17): the percussionist's techniques, GENERATED from the ARO catalog
// (bank/aro_percussion_catalog.json — piece #2's key-by-key map of Spitfire Abbey Road Orchestra
// Percussion, carried) and this piece's selection (bank/perc_selection.json — which instruments, on
// which channel), written into sandbox/instruments.js as a generated block, ARO_PERC, applied at load
// by applyAroPerc(). Spitfire's All-in-One preset is byNote — the KEY is the articulation, loudness is
// velocity, no keyswitch and no CC prelude — so one technique per instrument × beater: its range is
// that beater's block of keys, and its `keys` table says what each key is ("Low · Hit L" …). One
// Spitfire instance per instrument = one Reaper track per selected instrument, filtering on its
// channel (Spitfire cannot switch instruments by MIDI — piece #2's decision 5). While the selection is
// empty the block is inert and the `main` placeholder stays. Re-run after every change to the selection.
//
//   node tools/apply_perc.js [--selection bank/perc_selection.json] [--dry]
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
const opt = (k, d) => { const i = args.indexOf('--' + k); return i >= 0 && args[i + 1] != null ? args[i + 1] : d; };
const CATALOG = path.join(ROOT, 'bank', 'aro_percussion_catalog.json');
const SELECTION = path.resolve(ROOT, opt('selection', 'bank/perc_selection.json'));
const RECIPE = path.join(ROOT, 'sandbox', 'instruments.js');
const CAT = JSON.parse(fs.readFileSync(CATALOG, 'utf8')), SEL = JSON.parse(fs.readFileSync(SELECTION, 'utf8'));
const die = m => { console.error('apply_perc: ' + m); process.exit(1); };
const slugify = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
const DEFAULT_PORT = SEL.port || 'LGPerc';

const insts = [], used = {};
for (const item of SEL.instruments || []) {
  const it = typeof item === 'string' ? { slug: item } : item;
  const e = CAT.instruments[it.slug]; if (!e) die(it.slug + ': not in the catalog');
  const a = e.allInOne;
  if (!Array.isArray(a) || !a.some(k => k && Number.isFinite(k.midi))) die(it.slug + ': status "' + e.status + '" — the catalog has no keys for it; map it first (catalog _meta.walkthrough)');
  const port = it.port || DEFAULT_PORT, ch = it.channel;
  if (!Number.isInteger(ch) || ch < 1 || ch > 16) die(it.slug + ': channel must be 1–16 (got ' + ch + ')');
  used[port] = used[port] || {}; if (used[port][ch]) die(it.slug + ': channel ' + ch + ' on ' + port + ' is already ' + used[port][ch]); used[port][ch] = it.slug;
  const byBeater = new Map();
  for (const k of a) {
    if (!k || !Number.isFinite(k.midi)) continue;
    const b = k.beater || '';
    if (it.beaters && !it.beaters.includes(b)) continue;
    if (!byBeater.has(b)) byBeater.set(b, []);
    byBeater.get(b).push(k);
  }
  if (!byBeater.size) die(it.slug + ': the beaters filter ' + JSON.stringify(it.beaters) + ' matches none of ' + JSON.stringify(e.beaters));
  const techniques = [];
  for (const [b, ks] of byBeater) {
    ks.sort((x, y) => x.midi - y.midi);
    const q = { key: b ? it.slug + '_' + slugify(b) : it.slug, label: e.name + (b ? ' — ' + b : ''), channel: ch, kind: 'key', loud: 'vel' };   // 1m.4.1: a Spitfire instrument is BY KEY (the key is the sound), loud by velocity
    if (port !== DEFAULT_PORT) q.port = port;
    q.rangeLow = ks[0].midi; q.rangeHigh = ks[ks.length - 1].midi;
    q.keys = ks.map(k => ({ midi: k.midi, label: Object.entries(k).filter(([f, v]) => !['note', 'midi', 'beater'].includes(f) && v != null && v !== '').map(([, v]) => String(v)).join(' · ') }));
    techniques.push(q);
  }
  insts.push({ slug: it.slug, name: e.name, library: e.library, status: e.status, port, channel: ch, techniques });
}

const BEGIN = '// ---- ARO PERCUSSION (generated by tools/apply_perc.js from bank/perc_selection.json — do not edit by hand) ----';
const END = '// ---- end of the ARO percussion ----';
const L = [];
L.push('const ARO_PERC = {   // ' + insts.length + ' instrument(s) selected ' + new Date().toISOString().slice(0, 10) + (insts.length ? ': ' + insts.map(I => I.slug + ' ch' + I.channel + (I.port !== DEFAULT_PORT ? '@' + I.port : '')).join(' · ') : ' — the placeholder voice stays'));
L.push('  port: ' + JSON.stringify(DEFAULT_PORT) + ',');
L.push('  instruments: [');
for (const I of insts) {
  L.push('    { slug: ' + JSON.stringify(I.slug) + ', name: ' + JSON.stringify(I.name) + ', library: ' + JSON.stringify(I.library) + ', status: ' + JSON.stringify(I.status) + ', port: ' + JSON.stringify(I.port) + ', channel: ' + I.channel + ', techniques: [');
  for (const q of I.techniques) {
    const { keys, ...rest } = q;
    L.push('      { ' + Object.entries(rest).map(([k, v]) => k + ': ' + JSON.stringify(v)).join(', ') + ',');
    L.push('        keys: ' + JSON.stringify(keys) + ' },');
  }
  L.push('    ] },');
}
L.push('  ],');
L.push('};');
// LGMF 2026-09-21 (RUNNING_LOG §212): the selection is ADDED beside the placeholder `main`, which STAYS the ordinary voice on its own
// channels. It used to REPLACE it — but his harmony takes carry 241 percussion notes on `main`, so replacing it would change the sound
// of everything already made. A hand-registered key (the claves of 1l.1) gives way to the generated one of the same key.
L.push('function applyAroPerc(all, sel) {   // the selection is ADDED beside the placeholder `main`, which stays the ordinary voice on its own channels; nothing selected → nothing changes');
L.push('  const P = all.percussion; if (!P || !sel || !sel.instruments || !sel.instruments.length) return;');
L.push('  const techs = [];');
L.push('  for (const I of sel.instruments) for (const q of I.techniques) techs.push(Object.assign({}, q, { keys: q.keys.slice() }));');
L.push('  const gen = new Set(techs.map(q => q.key));');
L.push('  P.techniques = P.techniques.filter(q => !gen.has(q.key)).concat(techs);');
L.push('  P.aroInstruments = sel.instruments.map(I => ({ slug: I.slug, name: I.name, port: I.port, channel: I.channel }));');
L.push('}');
L.push('applyAroPerc(INSTRUMENTS, ARO_PERC);');
const block = BEGIN + '\n' + L.join('\n') + '\n' + END + '\n';

let src = fs.readFileSync(RECIPE, 'utf8');
const i = src.indexOf(BEGIN), j = src.indexOf(END);
let out;
if (i >= 0 && j > i) out = src.slice(0, i) + block + src.slice(j + END.length + 1);
else {
  // first time: after the INSTRUMENTS table, BEFORE the measured blocks — a later measurement lands on top of the generated techniques
  let k = src.indexOf('// ---- MEASURED RANGES'); if (k < 0) k = src.indexOf('// Hardware capture input.');
  if (k < 0) throw new Error('anchor for the block not found in the recipe');
  out = src.slice(0, k) + block + '\n' + src.slice(k);
}
if (args.includes('--dry')) { console.log(block); console.log(insts.length + ' instrument(s) (dry run, nothing written)'); process.exit(0); }
fs.writeFileSync(RECIPE, out);
// prove the recipe still evaluates and the selection took
const I = vm.runInNewContext(out + '\n;INSTRUMENTS;', {});
const P = I.percussion;
console.log(insts.length + ' instrument(s) written into sandbox/instruments.js; the percussion lane at load: ' + P.techniques.length + ' technique(s), range ' + P.rangeLow + '–' + P.rangeHigh + ', port ' + P.port + ', channels ' + JSON.stringify(P.channels));
for (const q of P.techniques) console.log('  ' + q.key.padEnd(38) + ' ch' + q.channel + (q.port ? '@' + q.port : '') + '  ' + String(q.rangeLow != null ? q.rangeLow : P.rangeLow).padStart(3) + '–' + String(q.rangeHigh != null ? q.rangeHigh : P.rangeHigh).padEnd(3) + (q.keys ? '  ' + String(q.keys.length).padStart(2) + ' keys' : '') + '  ' + q.label);
