#!/usr/bin/env node
// apply_uvi_parts.js — PLAN 0c/0e (2026-09-17): the SI2 techniques' channels and ports, GENERATED FROM THE RACK. The recipe
// (sandbox/instruments.js) says which PRESET each technique lives in and, for a keyswitched preset, which key — knowledge; the
// running UVI instances say which PART (port, channel) holds each preset — fact, read through the bridge (tools/uvi_state.js info).
// This tool joins the two and writes the result into sandbox/instruments.js as a generated block, UVI_PARTS, applied at load by
// applyUviParts(): every technique gets its port + channel; `channels.main` is the ordinary's part; `channels.curve` are the extra
// copies of the ordinary preset (the curve parts, made by tools/uvi_edit.js clone). A preset in the rack with no technique, or a
// technique whose preset is not in the rack, is REPORTED — nothing is guessed. Re-run after any change to a UVI instance.
//
//   node tools/apply_uvi_parts.js [--only bassoon,horn] [--dry]
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm'), { execFileSync } = require('child_process');
const ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
const opt = (k, d) => { const i = args.indexOf('--' + k); return i >= 0 && args[i + 1] != null ? args[i + 1] : d; };
const RECIPE = path.join(ROOT, 'sandbox', 'instruments.js');

// which Reaper tracks hold each UVI instrument, in order (the second is the `b` instance on its own port)
const TRACKS = {
  bassoon: [{ track: 'Bassoon SI2', port: 'LGBassoon' }, { track: 'Bassoon SI2 b', port: 'LGBassoonb' }],
  horn:    [{ track: 'Horn SI2',    port: 'LGHorn' },    { track: 'Horn SI2 b',    port: 'LGHornb' }],
  trumpet: [{ track: 'Trumpet SI2', port: 'LGTrumpet' }, { track: 'Trumpet SI2 b', port: 'LGTrumpetb' }],
};
const only = opt('only', '') ? opt('only').split(',') : Object.keys(TRACKS);

// the recipe as it evaluates now (with the previous UVI_PARTS block, if any — the join below reads only the hand-written fields)
const src0 = fs.readFileSync(RECIPE, 'utf8');
const BEGIN = '// ---- UVI PARTS (generated by tools/apply_uvi_parts.js from the running rack — do not edit by hand) ----';
const END = '// ---- end of the UVI parts ----';
const stripBlock = s => { const i = s.indexOf(BEGIN), j = s.indexOf(END); return i >= 0 && j > i ? s.slice(0, i) + s.slice(j + END.length + 1) : s; };
const I = vm.runInNewContext(stripBlock(src0) + '\n;INSTRUMENTS;', {});

const unesc = s => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"');
function readParts(track) {
  const out = execFileSync('node', [path.join(ROOT, 'tools', 'uvi_state.js'), 'info', track], { encoding: 'utf8' });
  return JSON.parse(out).parts.filter(p => p.program).map(p => ({ part: p.part, ch: p.midiChannel + 1, program: unesc(p.program) }));
}

const GEN = {}; const report = [];
for (const inst of only) {
  const R = I[inst]; if (!R) { report.push(inst + ': no recipe entry'); continue; }
  const parts = [];
  for (const t of TRACKS[inst]) { let ps; try { ps = readParts(t.track); } catch (e) { report.push(inst + ': ' + t.track + ' could not be read (' + (e.stderr || e.message).toString().trim().split('\n').pop() + ')'); continue; } for (const p of ps) parts.push({ ...p, port: t.port, track: t.track }); }
  const byPreset = {}; for (const p of parts) (byPreset[p.program] = byPreset[p.program] || []).push(p);
  const techs = {}; const used = new Set();
  for (const q of R.techniques) {
    if (!q.preset) { report.push(inst + '/' + q.key + ': no `preset` in the recipe — cannot be placed'); continue; }
    const hits = byPreset[q.preset];
    if (!hits) { report.push(inst + '/' + q.key + ': preset "' + q.preset + '" is not loaded in the rack'); continue; }
    const p = hits[0]; used.add(q.preset);
    techs[q.key] = { port: p.port, channel: p.ch };
  }
  const ordKey = R.ordinary || 'ord'; const ordQ = R.techniques.find(q => q.key === ordKey);
  const copies = ordQ && byPreset[ordQ.preset] ? byPreset[ordQ.preset].slice(1).map(p => ({ port: p.port, ch: p.ch })) : [];
  for (const [name, hits] of Object.entries(byPreset)) if (!used.has(name)) report.push(inst + ': part ' + hits.map(h => h.track + ' ' + h.part).join(', ') + ' holds "' + name + '", which no technique names');
  GEN[inst] = { techniques: techs, main: techs[ordKey] || null, curve: copies, curveTechniques: [ordKey], parts: parts.map(p => ({ track: p.track, part: p.part, ch: p.ch, program: p.program })) };
}

// the block
const L = [];
L.push('const UVI_PARTS = {   // read from the running rack ' + new Date().toISOString().slice(0, 16).replace('T', ' ') + ' — ' + Object.entries(GEN).map(([k, g]) => k + ': ' + Object.keys(g.techniques).length + ' techniques on ' + g.parts.length + ' parts, ' + g.curve.length + ' curve copies').join(' · '));
for (const [inst, g] of Object.entries(GEN)) {
  L.push('  ' + inst + ': {');
  L.push('    techniques: { ' + Object.entries(g.techniques).map(([k, v]) => k + ': ' + JSON.stringify(v)).join(', ') + ' },');
  L.push('    main: ' + JSON.stringify(g.main) + ', curve: ' + JSON.stringify(g.curve) + ', curveTechniques: ' + JSON.stringify(g.curveTechniques) + ',');
  L.push('    parts: [' + g.parts.map(p => JSON.stringify(p)).join(',\n            ') + '],');
  L.push('  },');
}
L.push('};');
L.push('function applyUviParts(all, gen) {   // the rack decides the channel and the port of every SI2 technique; the recipe keeps the preset and the keyswitch');
L.push('  for (const [inst, g] of Object.entries(gen || {})) {');
L.push('    const R = all[inst]; if (!R || !R.techniques) continue;');
L.push('    for (const q of R.techniques) { const v = g.techniques[q.key]; if (!v) { if (q.channel == null && g.main) q.channel = g.main.channel; continue; } q.channel = v.channel; if (v.port !== R.port) q.port = v.port; else delete q.port; q.placed = true; }');
L.push('    if (g.main) R.channels = { main: g.main.channel, mainPort: g.main.port !== R.port ? g.main.port : undefined, curve: g.curve.map(c => ({ port: c.port, ch: c.ch })), curveTechniques: g.curveTechniques.slice() };');
L.push('    R.uviParts = g.parts.slice();');
L.push('  }');
L.push('}');
L.push('applyUviParts(INSTRUMENTS, UVI_PARTS);');
const block = BEGIN + '\n' + L.join('\n') + '\n' + END + '\n';

let out; const base = stripBlock(src0);
{ // before the ARO percussion block if present, else before the measured blocks, else before the hardware lines
  let k = base.indexOf('// ---- ARO PERCUSSION'); if (k < 0) k = base.indexOf('// ---- MEASURED RANGES'); if (k < 0) k = base.indexOf('// Hardware capture input.');
  if (k < 0) throw new Error('anchor for the block not found in the recipe');
  out = base.slice(0, k) + block + '\n' + base.slice(k);
}
if (report.length) { console.log('REPORT — nothing guessed:'); for (const r of report) console.log('  ' + r); }
if (args.includes('--dry')) { console.log(block); process.exit(0); }
fs.writeFileSync(RECIPE, out);
const J = vm.runInNewContext(out + '\n;INSTRUMENTS;', {});
for (const inst of Object.keys(GEN)) {
  const R = J[inst];
  console.log(inst + ': ' + R.techniques.filter(q => q.placed).length + '/' + R.techniques.length + ' techniques placed · main ' + JSON.stringify(R.channels.main) + (R.channels.mainPort ? '@' + R.channels.mainPort : '') + ' · curve ' + R.channels.curve.map(c => c.port + ':' + c.ch).join(' '));
  for (const q of R.techniques) console.log('  ' + q.key.padEnd(18) + (q.placed ? (q.port || R.port).padEnd(11) + ' ch ' + String(q.channel).padStart(2) : '  — NOT PLACED —        ') + '  ' + (q.ks != null ? 'ks ' + q.ks + '  ' : '') + (q.preset || ''));
}
process.exit(report.length ? 1 : 0);
