#!/usr/bin/env node
// apply_bend_ranges.js — PLAN 1f step 1 (2026-09-07): the measured pitch-bend ranges (bank/bend_ranges.json, from
// `balance_schedule.js --bend` + `analyze_bend.py`) written into sandbox/instruments.js as a generated block, MEASURED_BEND,
// applied at load by applyMeasuredBend(): `bendRangeSt` (semitones per full bend, the sampler's) replaces the recipe's provisional
// value on every instrument the probe read; `bendMeasured: true` marks it; `bendMutableByMidi` says whether RPN 0 changed it.
// The player's own range (`playerBendSt`, his rule: within a semitone) is not measured — it stays as written in the recipe.
// Re-run after every bend probe. Mirrors tools/apply_ranges.js.
//
//   node tools/apply_bend_ranges.js [--in bank/bend_ranges.json] [--recipe sandbox/instruments.js] [--dry]
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);
const opt = (k, d) => { const i = args.indexOf('--' + k); return i >= 0 && args[i + 1] != null ? args[i + 1] : d; };
const IN = path.resolve(ROOT, opt('in', 'bank/bend_ranges.json')), RECIPE = path.resolve(ROOT, opt('recipe', 'sandbox/instruments.js'));
const R = JSON.parse(fs.readFileSync(IN, 'utf8'));
const BEGIN = '// ---- MEASURED BEND RANGES (generated by tools/apply_bend_ranges.js — do not edit by hand) ----', END = '// ---- end of the measured bend ranges ----';

const lines = ['const MEASURED_BEND = {   // measured ' + (R.measuredAt || '').slice(0, 16) + ' (' + R.wav + '): semitones per full bend on the ordinary voice; RPN 0 honoured = MIDI can change it'];
let count = 0, skipped = [];
for (const [inst, d] of Object.entries(R.instruments || {})) {
    if (d.rangeSt == null || d.bendDead) { skipped.push(inst + ' (' + d.verdict + ')'); lines.push('  ' + inst + ': null,   // ' + d.verdict + ' — the recipe\'s provisional value stays'); continue; }
    lines.push('  ' + inst + ': { rangeSt: ' + d.rangeSt + ', spreadSt: ' + d.rangeSpreadSt + ', mutableByMidi: ' + (d.rpnHonoured === true) + ', residueCents: ' + d.residueCents + ', pitch: ' + d.pitch + ' },' +
               (d.verdict !== 'OK' ? '   // ' + d.verdict : ''));
    count++;
}
lines.push('};');
lines.push('function applyMeasuredBend(all, measured) {   // the measured range replaces the provisional bendRangeSt');
lines.push('  for (const [inst, m] of Object.entries(measured || {})) {');
lines.push('    const I = all[inst]; if (!I || !m) continue;');
lines.push('    I.bendRangeSt = m.rangeSt; I.bendMeasured = true; I.bendMutableByMidi = !!m.mutableByMidi; I.bendResidueCents = m.residueCents;');
lines.push('  }');
lines.push('}');
lines.push('applyMeasuredBend(INSTRUMENTS, MEASURED_BEND);');
const block = BEGIN + '\n' + lines.join('\n') + '\n' + END + '\n';

let src = fs.readFileSync(RECIPE, 'utf8');
const i = src.indexOf(BEGIN), j = src.indexOf(END);
let out;
if (i >= 0 && j > i) out = src.slice(0, i) + block + src.slice(j + END.length + 1);
else {
    // first time: after the measured ranges block, before the hardware-capture lines at the file's end
    const anchor = '// Hardware capture input.';
    const k = src.indexOf(anchor);
    if (k < 0) throw new Error('anchor for the block not found in the recipe');
    out = src.slice(0, k) + block + '\n' + src.slice(k);
}
if (args.includes('--dry')) { console.log(block); console.log(count + ' measured instruments' + (skipped.length ? ', skipped: ' + skipped.join(', ') : '') + ' (dry run, nothing written)'); process.exit(0); }
fs.writeFileSync(RECIPE, out);
// prove the recipe still evaluates and the ranges took
const I = vm.runInNewContext(out + '\n;INSTRUMENTS;', {});
console.log(count + ' measured instruments written into ' + path.relative(ROOT, RECIPE) + (skipped.length ? ' (skipped: ' + skipped.join(', ') + ')' : '') + '; applied at load:');
for (const inst of Object.keys(R.instruments || {})) { const q = I[inst]; if (q) console.log('  ' + inst.padEnd(14) + ' bendRangeSt ' + q.bendRangeSt + (q.bendMeasured ? ' (measured' + (q.bendMutableByMidi ? ', RPN honoured' : ', RPN ignored') + ', residue ' + q.bendResidueCents + ' c)' : ' (provisional)') + ' · playerBendSt ' + q.playerBendSt); }
