#!/usr/bin/env node
// gen_apply_trims.js — PLAN 1b.3 (2026-09-19): write bank/trims.json into reaper/bridge/jobs/apply_trims.lua.
//
//   node tools/gen_apply_trims.js [--in bank/trims.json] [--dry]
//
// 0d's version of that job had its table typed in by hand from bank/balance.json (§58). This generates it,
// for one reason above the others: **the table has to name every track an instrument sounds through**, and
// that set has grown since 0d was written. `Horn SI2 high` and `Horn SI2 b high` — the ReaPitch path that
// makes the horn audible above F4 (1a.1, §68) — did not exist when the old table was typed, so they have
// never carried a trim and still sit at −0.01 dB. Applying the new numbers without them would leave every
// horn note above F4 twelve decibels louder than every note below it, at the exact seam the piece lives on
// (five of the six horn notes in the reference chords are in the raised part).
//
// It rewrites ONLY the header comment and the TRIMS table; the body of the job — find the track, set the
// fader, put the remainder in a stock JS Volume, read every value back, never save — is kept byte-identical,
// because it is proven and this tool has no business touching it.
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const DRY = process.argv.includes('--dry');
const TRIMS = JSON.parse(fs.readFileSync(path.join(ROOT, arg('in', 'bank/trims.json')), 'utf8'));
const PERC = JSON.parse(fs.readFileSync(path.join(ROOT, 'bank', 'perc_rack.json'), 'utf8'));
const JOB = path.join(ROOT, 'reaper', 'bridge', 'jobs', 'apply_trims.lua');

// every Reaper track an instrument sounds through. The `b` instances are the same instrument's curve
// copies; the two `high` tracks are the ReaPitch path of 1a.1 and are NEW since 0d's table.
const PITCHED_TRACKS = {
    english_horn: ['English Horn XS'],
    bassoon: ['Bassoon SI2', 'Bassoon SI2 b'],
    horn: ['Horn SI2', 'Horn SI2 b', 'Horn SI2 high', 'Horn SI2 b high'],
    trumpet: ['Trumpet SI2', 'Trumpet SI2 b'],
    bowed_vibraphone: ['Vibraphone XS'],
    cello: ['Cello XS'],
    double_bass: ['Bass XS'],
};
const percTrack = {};
for (const t of PERC.tracks) if (t.catalog) percTrack[t.catalog] = t.track;

const rows = [];
for (const r of TRIMS.instruments) {
    if (r.skipped) continue;
    const tracks = r.family === 'pitched' ? PITCHED_TRACKS[r.inst] : (percTrack[r.inst] ? [percTrack[r.inst]] : null);
    if (!tracks) { console.error('no rack track for ' + r.inst + ' — SKIPPED'); continue; }
    for (const name of tracks) {
        rows.push({ name, faderDb: r.faderDb, extraDb: r.jsVolumeDb || 0, label: r.label,
                    was: r.currentTrimDb, change: r.deltaDb });
    }
}

const f2 = n => (n >= 0 ? '' : '') + n.toFixed(2);
const table = 'local TRIMS = {\n'
    + rows.map(r => `  { name = ${JSON.stringify(r.name)}, faderDb = ${f2(r.faderDb)}, extraDb = ${f2(r.extraDb)} },`
        + `   -- ${r.label}: was ${f2(r.was)}, ${r.change >= 0 ? '+' : ''}${f2(r.change)}`).join('\n')
    + '\n}\n';

const header = `-- apply_trims.lua — PLAN 1b.3 (2026-09-19): the ABSOLUTE trims onto the rack.
-- GENERATED by tools/gen_apply_trims.js from bank/trims.json — do not edit the table by hand.
-- Idempotent, self-reporting, and it NEVER saves: his CTRL+S.
--
-- The target (RUNNING_LOG §83): a ${TRIMS.target.voices}-voice tutti at ${TRIMS.target.tuttiLufs} LUFS-S, so each voice at
-- ${TRIMS.target.perVoiceLufs} LUFS = ${TRIMS.target.perVoiceCardDb} dB on the instrument card's scale. Every instrument in this table
-- comes DOWN: the rack was 7–21 dB hot because 0d balanced it relatively, through a REC bus trimmed
-- 12 dB down, with nothing saying how loud the ensemble should BE (§76).
--
-- Each row: the Reaper FADER carries up to +12 dB (its ceiling); any remainder goes into a stock
-- "JS: Volume Adjustment" (utility/volume) FX on the track — Reaper-side, no MIDI binding, so no CC7 can
-- ever overwrite it (ARO's own gain is bound to CC7 and tops out at unity — §58; #5's SI2 parts had the same
-- trap). A track with no remainder gets no FX; an existing one is set to 0 rather than removed.
-- The SI2 \`b\` instances carry their instrument's trim too — the same instrument, its curve copies — and so
-- do **Horn SI2 high** and **Horn SI2 b high**, the ReaPitch path of 1a.1, which 0d's hand-typed table
-- predated and which have therefore never been trimmed at all.
--   node tools/reaper_job.js run reaper/bridge/jobs/apply_trims.lua
local JS_NAME = 'utility/volume'
`;

const cur = fs.readFileSync(JOB, 'utf8');
const EOL = cur.includes('\r\n') ? '\r\n' : '\n';
const SPLIT = 'local function findTrack(name)';
const at = cur.indexOf(SPLIT);
if (at < 0) throw new Error('could not find the job body — aborting rather than guessing');
const body = cur.slice(at);
const next = (header + table).replace(/\n/g, EOL) + body;

console.log('APPLY_TRIMS — ' + rows.length + ' track rows from ' + TRIMS.instruments.filter(r => !r.skipped).length + ' instruments\n');
for (const r of rows) {
    console.log('  ' + r.name.padEnd(24) + 'fader ' + f2(r.faderDb).padStart(7)
        + (r.extraDb ? '  + JS ' + f2(r.extraDb).padStart(6) : '            ')
        + '   (was ' + f2(r.was).padStart(6) + ', ' + (r.change >= 0 ? '+' : '') + f2(r.change) + ')');
}
const newTracks = rows.filter(r => /high$/.test(r.name));
if (newTracks.length) console.log('\n  NEW since 0d’s table: ' + newTracks.map(r => r.name).join(' · ')
    + ' — the ReaPitch path, never trimmed until now');

if (DRY) { console.log('\ndry run — apply_trims.lua not written'); process.exit(0); }
fs.writeFileSync(JOB, next);
console.log('\nwrote reaper/bridge/jobs/apply_trims.lua (header + table regenerated; the body is byte-identical)');
