#!/usr/bin/env node
// make_reference_audio.js — PLAN 1b.1 (2026-09-19): the rack's CALIBRATION REFERENCE, generated.
//
//   probes/reference/pink-20dBFS.wav    30 s pink noise, −20.00 dBFS RMS per channel
//   probes/reference/tone1k-20dBFS.wav  30 s 1 kHz sine, −20.00 dBFS RMS per channel (peak −17.0)
//
// WHY A GENERATED FILE AND NOT A PLUGIN (decision 1b.0, RUNNING_LOG §76). The reference has to be the one
// thing in the chain whose level is KNOWN, so it must be a fixed sample of known RMS, not a plugin whose
// gain is another parameter to be trusted. −20 dBFS RMS pink noise is the K-20 monitor reference (Katz;
// SMPTE RP 200) — the orchestral/film alignment the piece is being calibrated to; the 1 kHz tone at the
// same RMS is the METER's proof, because its expected readings are exact numbers rather than estimates:
//
//   flat RMS per channel    −20.00 dBFS          (the digital chain has unity gain)
//   BS.1770, MONO           −20.0 LUFS           (the −0.691 offset exists to make this identity hold)
//   BS.1770, STEREO         −17.0 LUFS           (+3.01: two correlated channels)
//   true peak               −17.0 dBTP           (a sine: peak = RMS + 3.01)
//
// Pink noise at the SAME flat RMS measures −17.5 LUFS stereo (ffmpeg ebur128, 2026-09-19) — 0.5 dB under the
// tone, because K-weighting trades the bottom octaves it removes against the +4 dB shelf it adds on top. That
// number is MEASURED, not asserted, which is why the TONE is the pass/fail and the noise is the monitor level.
//
// DETERMINISTIC. The noise comes from a seeded mulberry32 (the generator morph.js uses), so the files can
// be deleted and regenerated byte-identical — that is why they are gitignored rather than committed, and
// why bank/reference.json records each file's SHA-256. A different seed is a different reference: don't.
//
// 44100 Hz (the rack's SAMPLERATE), stereo, 24-bit PCM. The tone holds exactly 30000 cycles in exactly
// 1323000 samples, so it begins and ends at a zero crossing and needs no fade.
//
//   node tools/make_reference_audio.js            # write both, print the measurements
//   node tools/make_reference_audio.js --check    # regenerate in memory and compare against what is on disk
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'probes', 'reference');
const SR = 44100;
const SECONDS = 30;
const RMS_DBFS = -20;
const SEED = 20260919;
const CHECK = process.argv.includes('--check');

const N = SR * SECONDS;
const dbfs = x => 20 * Math.log10(Math.max(x, 1e-12));

// the seeded generator of morph.js, so the noise is reproducible from the seed alone
function mulberry32(a) {
    return function () {
        a |= 0; a = (a + 0x6D2B79F5) | 0;
        let t = Math.imul(a ^ (a >>> 15), 1 | a);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

// Paul Kellet's refined 7-pole pinking filter: ±0.05 dB from 9 Hz to 20 kHz — flat enough that the
// reference's spectrum is a fact about pink noise and not about the filter.
function pink(n, seed) {
    const rng = mulberry32(seed);
    const out = new Float64Array(n);
    let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
    for (let i = 0; i < n; i++) {
        const w = rng() * 2 - 1;
        b0 = 0.99886 * b0 + w * 0.0555179;
        b1 = 0.99332 * b1 + w * 0.0750759;
        b2 = 0.96900 * b2 + w * 0.1538520;
        b3 = 0.86650 * b3 + w * 0.3104856;
        b4 = 0.55000 * b4 + w * 0.5329522;
        b5 = -0.7616 * b5 - w * 0.0168980;
        out[i] = b0 + b1 + b2 + b3 + b4 + b5 + b6 + w * 0.5362;
        b6 = w * 0.115926;
    }
    return out;
}

function rmsOf(x) { let s = 0; for (let i = 0; i < x.length; i++) s += x[i] * x[i]; return Math.sqrt(s / x.length); }
function peakOf(x) { let p = 0; for (let i = 0; i < x.length; i++) { const a = Math.abs(x[i]); if (a > p) p = a; } return p; }

// 24-bit PCM, stereo, the same signal in both channels (a standard alignment reference: correlated, so the
// stereo LUFS is the mono reading + 3.01 exactly, which is itself a check on the meter)
function writeWav24(mono) {
    const n = mono.length, ch = 2, bytes = 3;
    const dataLen = n * ch * bytes;
    const buf = Buffer.alloc(44 + dataLen);
    buf.write('RIFF', 0); buf.writeUInt32LE(36 + dataLen, 4); buf.write('WAVE', 8);
    buf.write('fmt ', 12); buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(ch, 22);
    buf.writeUInt32LE(SR, 24); buf.writeUInt32LE(SR * ch * bytes, 28);
    buf.writeUInt16LE(ch * bytes, 32); buf.writeUInt16LE(bytes * 8, 34);
    buf.write('data', 36); buf.writeUInt32LE(dataLen, 40);
    const FULL = 8388607;   // 2^23 − 1: the positive full scale a 24-bit sample can hold
    let o = 44;
    const quantised = new Float64Array(n);
    for (let i = 0; i < n; i++) {
        let v = Math.round(mono[i] * FULL);
        if (v > FULL) v = FULL; if (v < -FULL - 1) v = -FULL - 1;
        quantised[i] = v / FULL;
        for (let c = 0; c < ch; c++) {
            buf.writeUInt8(v & 0xFF, o); buf.writeUInt8((v >> 8) & 0xFF, o + 1); buf.writeUInt8((v >> 16) & 0xFF, o + 2);   // the MSB is the two's-complement byte, so it is written UNSIGNED
            o += 3;
        }
    }
    return { buf, quantised };
}

function build(kind) {
    let x;
    if (kind === 'pink') {
        x = pink(N, SEED);
    } else {
        x = new Float64Array(N);
        const amp = Math.pow(10, RMS_DBFS / 20) * Math.SQRT2;     // RMS −20 dBFS → peak −17.0 dBFS
        for (let i = 0; i < N; i++) x[i] = amp * Math.sin(2 * Math.PI * 1000 * i / SR);
    }
    if (kind === 'pink') {                                         // the tone is already exact; the noise is scaled to the target
        const g = Math.pow(10, RMS_DBFS / 20) / rmsOf(x);
        for (let i = 0; i < N; i++) x[i] *= g;
    }
    const { buf, quantised } = writeWav24(x);
    return { buf, rms: rmsOf(quantised), peak: peakOf(quantised) };
}

fs.mkdirSync(OUT, { recursive: true });
const FILES = [
    { kind: 'pink', name: 'pink-20dBFS.wav', what: '30 s pink noise, the K-20 monitor reference' },
    { kind: 'tone', name: 'tone1k-20dBFS.wav', what: '30 s 1 kHz sine, the meter’s proof' },
];

const rows = [];
let drift = false;
for (const F of FILES) {
    const { buf, rms, peak } = build(F.kind);
    const file = path.join(OUT, F.name);
    const sha = crypto.createHash('sha256').update(buf).digest('hex');
    let status = 'written';
    if (CHECK) {
        const on = fs.existsSync(file) ? crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex') : null;
        status = on === sha ? 'IDENTICAL' : (on ? 'DIFFERS' : 'MISSING');
        if (status !== 'IDENTICAL') drift = true;
    } else {
        fs.writeFileSync(file, buf);
    }
    rows.push({ file: 'probes/reference/' + F.name, what: F.what, seconds: SECONDS, sampleRate: SR, bits: 24, channels: 2,
                rmsDbfs: Math.round(dbfs(rms) * 1000) / 1000, peakDbfs: Math.round(dbfs(peak) * 1000) / 1000, sha256: sha, status });
}

console.log('THE CALIBRATION REFERENCE — ' + SR + ' Hz, stereo, 24-bit, seed ' + SEED + (CHECK ? '   [--check: nothing written]' : '') + '\n');
for (const r of rows) {
    console.log('  ' + r.file.padEnd(38) + 'RMS ' + r.rmsDbfs.toFixed(3) + ' dBFS · peak ' + r.peakDbfs.toFixed(2)
        + ' dBFS   ' + r.status + '\n' + ' '.repeat(40) + r.what + '  sha ' + r.sha256.slice(0, 16) + '…');
}
console.log('\nEXPECTED WHEN RECORDED THROUGH A UNITY CHAIN (the pass of 1b.1):');
console.log('  the tone    flat RMS −20.00 dBFS · BS.1770 mono −20.0 LUFS · stereo −17.0 LUFS · true peak −17.0 dBTP');
console.log('  the noise   flat RMS −20.00 dBFS · its LUFS is MEASURED (pink K-weights down ~1–2 dB), not asserted');
if (CHECK && drift) { console.error('\nthe files on disk are NOT what this seed generates — regenerate, or find out who changed them'); process.exit(1); }
if (CHECK) console.log('\nboth files on disk are byte-identical to what the seed generates.');
